Repository do3-2021/dosm, pull requests merged in 2022-02, with the labels that each got.

#14 Add ports panel and miniframe
  README.md
  ports/__init__.py
  ports/frame.py
  ports/mini_frame.py
  ports/read.py
Labels: enhancement

#20 Connected users
  connected_users/__init__.py
  connected_users/frame.py
  connected_users/mini_frame.py
Labels: enhancement

#23 [PROJECT] rename classes and files
  connected_users/summary_frame.py
  connected_users/tab_frame.py
  home/base_summary_frame.py
  home/tab_frame.py
  integrator/__init__.py
  integrator/base_frame.py
  ports/summary_frame.py
  ports/tab_frame.py
  process/tab_frame.py
Labels: code cleaning

#24 [integrator] integrate connected users
  README.md
  connected_users/tab_frame.py
  integrator/__init__.py
Labels: documentation

#22 Login history
  loginhistory/__init__.py
  loginhistory/extractor.py
  loginhistory/frame.py
Labels: enhancement

#25 [integrator, login_history] Integrate login_history
  README.md
  integrator/__init__.py
  login_history/__init__.py
  login_history/extractor.py
  login_history/tab_frame.py
  loginhistory/frame.py
  utils.py
Labels: enhancement, code cleaning

#27 Everything ( seems to ) work fine, maybe there is a need for more content ?
  ipc/__init__.py
  ipc/summary_frame.py
  ipc/tab_frame.py
  ipc/utils.py
Labels: enhancement

#38 feat: fix/refactor some features & add get logs command from cli
  cli/logs.py
  cli/utils.py
Labels: enhancement, code cleaning

#41 fix: delete .Rhistory file for #40
  .Rhistory
Labels: bug

#39 added sumary frame, basically just removed some columns
  login_history/summary_frame.py
Labels: enhancement

#49 Summary frame wrong value printed
  login_history/summary_frame.py
Labels: bug

#47 [integrator] add save and load methods
  integrator/__init__.py
Labels: enhancement
